services:
  # api holds all of our backend code
  api:
    image: llm_lab/backend
    ports:
      - 8000:8000
    environment:
      - LLM_LAB_APP_ENV=production
      - LLM_LAB_CORS_ALLOWED_ORIGINS=localhost,127.0.0.1,localhost:3001
      - LLM_LAB_DB_NAME=db.sqlite
      - LLM_LAB_OUTPUT_DIR=output/
      - LLM_LAB_HF_API_KEY=...
  # app holds our vue frontend
  app:
    image: llm_lab/frontend
    environment:
      - VUE_APP_API_URL=http://localhost:8000
      - NODE_ENV=production
    ports:
      - 3001:8080
